travis:
  secure:
    BINSTAR_TOKEN: JCuR9rJvyU+Vc2hCnH8NJkr8KYJCC/RnTUWg7ai+SUVXDmWEse+VxXEBuowqPO/8KvvvUKIE7MbEW2NFnLu4juA7wpYE0dVPmiyZW+VHsorbagdM4EKN2wyXN84ilPRoxKDQpfa+o/NMYQExVXDlNYiFgSOKLg+7Nh4G92spvKh0uHBTJx+3MPY2IABZpQ7k2eImJ5B/H1vBZn53exsJeauwqndJ2H99ucbxejvb1OkTj/CYy9D+QdWvxHNJ21W3rCkicCn7xYonQXVoMCQ1CJb+GcLfoxQaXxjFptsMR+1CK6lo475UVCWhXxz7zFL1rWMLoNqWgLmaXtGQqNTIR6y50MIW6pG3efld6EAOUr6C6dynfca9JqtHrV4KusJ8e0Z45Y/dbYsvjkN2tvMez4FOsF+P9kiQJSQlm1jkQh4TYZewcS/3APogoZNPzCtBivANtBqF+o5PFH/VPRa7lt/9+jY2VjSWWkEPfTMaMN1yfLsPyJIwpLWI2PleTRgeT4u/yGljIV1sATVRRFHbfsyhL2zwXZgOgYM+cUNI8tZmRv0gpk7Zke8hQvMOETIQjNyQYAKh4LO4zKIwQcITrp116fJvY6JaJa2qHi1PdfdMpbJrwmyspqle4fsBF619LNILhEIzFc0mJE3Krw9EsWy3U8Ml+TSqoE9s6PIMqKk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
